# Site settings
title: Megatux's personal site
email: megatux@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Latest(?) information about myself, posts, etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://megatux.me" # the base hostname & protocol for your site
twitter_username: megatux
github_username:  megatux
devto_username:  megatux

# Build settings
markdown: kramdown

# theme: jekyll-theme-architect
